Better Speeding check system
esx-framework/esx_dmvschool pull request #39
Opened 2024-01-01 09:32 UTC by CommanderBALA

2024-01-16 18:02 UTC, Gellipapa requested changes

2024-01-16 18:02 UTC, Gellipapa commented on client/main.lua
> +						sleep = Config.SpeedingErrorDelay;
remove please this ; not a javascript :)

2024-01-16 18:02 UTC, Gellipapa commented on client/main.lua
> +					sleep = 1500;
remove please this ; not a javascript :)

2024-01-16 18:02 UTC, Gellipapa commented on client/main.lua
> +						sleep = Config.SpeedingErrorDelay;
I'm not sure it's a good idea to allow the user to set sleep, because if you enter a small number of counts, the load can really increase. There should be some condition on how long to allow this.

2024-02-17 17:41 UTC, CommanderBALA reviewed
New fixed version

2024-02-17 17:41 UTC, CommanderBALA commented on client/main.lua
> +						sleep = Config.SpeedingErrorDelay;
Done

2024-02-17 17:41 UTC, CommanderBALA commented on client/main.lua
> +					sleep = 1500;
Done

2024-02-27 18:54 UTC, Gellipapa approved these changes
Hi! @CommanderBALA Thank you for fix i will test, but code is approved. Thanks.

2024-04-02 10:16 UTC, bitpredator approved these changes

2024-09-28 14:52 UTC, Gellipapa commented
Fixes some error and refactor code #45

2024-09-28 14:52 UTC, closed without merging