V2
esx-framework/esx_dmvschool pull request #6
Opened 2023-02-05 12:18 UTC by Zan1456

2023-02-05 12:28 UTC, TheFantomas commented
Good job thanks we will review it

2023-02-09 21:20 UTC, TheFantomas commented
Rewrite functions in english please.

2023-02-09 21:20 UTC, TheFantomas commented
![image](https://user-images.githubusercontent.com/117121911/217941754-756a22cd-b340-4ead-a48a-961335ffe4cd.png)

2023-02-09 21:21 UTC, TheFantomas requested changes
Rewrite functions in english please.

2023-02-09 22:35 UTC, jbdevic requested changes

2023-02-09 22:35 UTC, jbdevic commented on html/scripts.js
> +      question: "If you're going 80 km/h, and you're approaching a residential area you must:",
I think the questions should be retrieved from an array in the config - would offer more personalization

2023-02-09 22:35 UTC, jbdevic commented on html/scripts.js
> +    $(".evaluation-title").html("Oops, that was probably nothing!")
make a translation file

2023-02-09 22:36 UTC, jbdevic commented
very nice job, I will surely try to improve the ui

2023-02-10 06:00 UTC, Zan1456 commented on html/scripts.js
> +    $(".evaluation-title").html("Oops, that was probably nothing!")
I will implement the changes soon.

2023-02-10 06:01 UTC, Zan1456 commented on html/scripts.js
> +      question: "If you're going 80 km/h, and you're approaching a residential area you must:",
I will implement the changes soon.

2023-02-11 17:40 UTC, Zan1456 commented
Anything else?

2023-04-02 09:46 UTC, Zan1456 commented
> sorry I've been busy, we will look at it this week

dump

2023-04-15 10:21 UTC, merged

2023-04-15 10:56 UTC, Zan1456 commented
I have 2 comments.
1. A file called questions_de.js remained in the html folder.
2. In the fxmanifest.lua file, version should be '2.0' and legacyversion should be '1.9.4'.

2023-04-15 11:10 UTC, TheFantomas commented
> I have 2 comments.
> 
> 1. A file called questions_de.js remained in the html folder.
> 2. In the fxmanifest.lua file, version should be '2.0' and legacyversion should be '1.9.4'.

Yes, yes we push it in to main (Whenit is fully functional) this branch was created only for testing.